# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Maxime Agor's blog"

# A description of your site for social meta tag, search engines, and feed.xml
description: "A blog about tech !"

# Tagline near the site title
tagline: "Explanations for noobs, by a noob."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://4rzael.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guides
  url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Maxime Agor"
author_bio: "Maxime is an engineer, open-source/hardware/data enthusiast, specialized in computing. From electronics to machine learning, quantum computing, or game dev, he likes to try stuff out."
author_url:  "https://4rzael.com"
author_location: "Bordeaux, France"
author_image: /images/authorimage.png

# Sidebar Add banner
banner_url: "https://4rzael.com"
banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "4rzael"
# facebook_username: "username"
# googleplus_username: "+username"
github_username: "4rzael"
# codepen_username: "username"
# dribbble_uername: "username"
# medium_username: "@username"
# instagram_username: "username"
# pinterest_username: "username"
linkedin_username: "maxime-agor-a14931158"
# weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
